oscomp/arceos

api/arceos_posix_api/src/imp/io.rs

The current `sys_writev` implementation does not return a correct error value if one of the write calls fails. Instead it adds the number of bytes written and any error codes, leading to a meaningless result. This PR fixes it by returning the error early.

Fix `sys_writev` return value in `arceos_posix_api`

---

Cargo.lock
api/arceos_posix_api/Cargo.toml
api/arceos_posix_api/src/imp/fd_ops.rs
api/arceos_posix_api/src/imp/path_link.rs

~*Temporarily using my own fork of `flatten_objects`, blocked by upstream: arceos-org/flatten_objects#2*~  
*The upstream has merged the PR but not yet released*
Some functions using `fd_table.count()` have incorrect behaviours: they assume `count` to be maximum file descriptor.
To fix it, I have added an `ids` method on upstream `FlattenObjects` to retrive all open file descriptors to make `copy_inner` work properly. The other two use cases are redundant since `Directory::from_fd` already checks the validity of the file descriptor.

Fix fd table behaviours

---

Cargo.lock
modules/axmm/Cargo.toml
modules/axmm/src/aspace.rs

See https://github.com/arceos-org/axmm_crates/pull/6
The upstream `axmm_crates` contains an implementation bug that causes `MemorySet::find_free_area` to degenerate. This PR patches `axmm_crates` to apply the fix.

Patch axmm_crates to use our fix & add `AddrSpace::check_region_access`

---

api/arceos_posix_api/src/imp/io.rs

Current implementation of `writev` does not respect errors from `write`. Meanwhile, its implementation is incorrect. According to the Linux manual:
> Buffers are processed in array order. This means that readv() completely fills iov[0] before proceeding to iov[1], and so on. (If there is insufficient data, then not all buffers pointed to by iov may be filled.) Similarly, writev() writes out the entire contents of iov[0] before proceeding to iov[1], and so on.
The old implementation will always process each buffer regardless of the result of the previous buffers.
This implementations checks the result of `sys_writev` with care, aborting the process early if one buffer fails to be fully written out.

Fix incorrect writev implementation

---

Cargo.lock
api/arceos_posix_api/Cargo.toml

Upstream [flatten_objects](https://github.com/arceos-org/flatten_objects) has released its fix.
#6

chore: update flatten_objects to 0.2.3

---

api/arceos_posix_api/Cargo.toml
modules/axmm/src/aspace.rs

`flatten_objects` version is updated to `0.2.3` to avoid unexpected build failure. This PR also includes a small fix to `check_region_access` where areas before the region to be checked could affect the result of the function.
See commits.

Update `flatten_objects` version & Fix `check_region_access`

---

Cargo.lock
modules/axfs/Cargo.toml
modules/axfs/src/api/file.rs

This PR upgrade `axio` to 0.1.1, which greatly improved `read_to_end` performance.
See https://github.com/arceos-org/axio/pull/1
- Previous time for running through all basic testcases except `sleep` (31 programs, each ~55KiB) on riscv64: 40.570544112s
- After this upgrade: 931.4604ms
- Previous time for running `/musl/busybox echo "Hello, World!"` (1.1MiB): 1.2493267s
- After this upgrade: 38.0424ms

Upgrade axio to 0.1.1 and utilize default_read_to_end

---

modules/axmm/src/backend/alloc.rs

This is an alternative for #10. This PR tries to avoid `pt.query` from returning zero address from source.
Previously we map lazily allocated memory area to a physical address `0`, and later `remap` to actual address on page fault. In this PR, we no longer create such invalid PTEs, but don't create any PTE at all.
See https://github.com/oscomp/arceos/pull/10#issuecomment-2711340462.
This PR mainly infects `clone` and `fork` so I'm showing these two testcases.
|x86_64|aarch64|riscv64|loongarch64|
|-|-|-|-|
|![图片](https://github.com/user-attachments/assets/727f8cda-e79a-4e57-8c4f-7d4502aed6fe)|![图片](https://github.com/user-attachments/assets/af1e9052-11b8-41c4-a2c2-5db38662e000)|![图片](https://github.com/user-attachments/assets/93827869-1936-4745-b282-8224864d667d)|![图片](https://github.com/us …

fix: don't map to zero address for lazily allocated memory area

---

modules/axmm/src/aspace.rs

Old implementation of `protect` does not populate the area first before calling the underlying method. Meanwhile, it does not take flags of `MemoryArea` into consideration.
This PR added `populate_area` method to populate a possibly unallocated memory area. Also call to `PageTable::protect` is replaced with `MemorySet::protect`.

Add populate_area, fix protect impl

---

api/arceos_posix_api/src/imp/io.rs

https://github.com/oscomp/arceos/commit/fd2f60140ac62d7ca6b560add8fd83f95f705a04 was lost during rebase.

chore: use write_impl

---

modules/axhal/src/arch/loongarch64/trap.S

This PR fixes support on LoongArch64 after we sync with upstream.
I compared latest code with previous https://github.com/oscomp/arceos/blob/old_main_0314/modules/axhal/src/arch/loongarch64/trap.S and found these lines missing. I also referred to https://github.com/oscomp/arceos/blob/main/modules/axhal/src/arch/riscv/trap.S and learned that this operation of saving kernel sp only needs to be performed when the exception handler exits after handling the user mode exception.
This issue currently only affects `yield` in basic testcases on LoongArch64, which involves repeated context switches.
Before this PR:
After this PR:
I have no idea why upstream accidentally dropped it. Maybe we should port it upstream later as well.

Fix kernel stack position on LoongArch64

---

api/arceos_posix_api/src/imp/fs.rs
modules/axfs/src/api/file.rs
modules/axfs/src/api/mod.rs
modules/axfs/src/fops.rs
modules/axfs/tests/test_common/mod.rs

This PR fixes several issues with opening directories:
1. Directories may be opened as files (`File::_open_at`).
2. Directories must be opened with execute permission, otherwise methods that require the directory to be executable (such as `open_dir_at`, `create_file` and `remove_file`) cannot be used.
3. `sys_openat` ignores `O_DIRECTORY`.
Also fixes a clippy warning and removes some unused fields in `OpenOptions`.
For the first issue, we just make `File::_open_at` return an error as long as `node` is a directory.
For the second, one might say it's correct to require execute permissions on the directory. But this does not mean that `O_EXEC` needs to be explicitly specified when opening the directory to access the directory contents. One might also ask why not automatically specify …

fix: open directory

---

Makefile
scripts/make/features.mk

We are implicitly forcing Rust apps to depend on `axstd` currently, since `ax_feat_prefix` and `lib_feat_prefix` is fixed to `axstd/` for Rust apps.
This PR fixes this by introducing a `NO_AXSTD` option (similar to `no_std` in Rust) to use `axfeat/` as `ax_feat_prefix` and `AX_LIB` to control `lib_feat_prefix` (note that this is separate from `NO_AXSTD` as apps might want to use `arceos_posix_api` as `AX_LIB`).
I initially wanted to change directly to `axfeat/`, but found that https://github.com/arceos-org/arceos-apps, on which our CI test is based, depends on `axstd`, so I had to give up.

feat: build without `axstd`

---

Cargo.lock
modules/axhal/src/arch/aarch64/context.rs
modules/axhal/src/arch/loongarch64/context.rs
modules/axhal/src/arch/riscv/context.rs
modules/axhal/src/arch/x86_64/context.rs

This PR generally improves the public api on `TrapFrame`, `UspaceContext` and `TaskContext`.
- A set of helper functions are added to `TrapFrame`.
- `Deref` and `DerefMut` is implemented for `UspaceContext` to allow easier access to the underlying `TrapFrame`.
- `tls()` and `set_tls()` are added to `TaskContext`.
These code are extracted from #23 by @Mivik.
- https://github.com/oscomp/starry-next/issues/5#issuecomment-2765277217
- https://github.com/oscomp/starry-next/discussions/30

feat(hal): improve context

---

modules/axns/src/lib.rs

This PR changes the `base` field in `AxNamespace` from a raw pointer to a address, to make this type `Send` and `Sync`. This is necessary for sharing namespaces, otherwise we would have to trick the compiler.

fix: make `AxNamespace` `Send + Sync`

---

api/arceos_posix_api/build.rs
modules/axhal/linker.lds.S
modules/axhal/src/arch/aarch64/context.rs
modules/axhal/src/arch/aarch64/mod.rs
modules/axhal/src/arch/aarch64/signal.S
modules/axhal/src/arch/aarch64/trap.S
modules/axhal/src/arch/aarch64/trap.rs
modules/axhal/src/arch/loongarch64/context.rs
modules/axhal/src/arch/loongarch64/mod.rs
modules/axhal/src/arch/loongarch64/signal.S
modules/axhal/src/arch/loongarch64/trap.rs
modules/axhal/src/arch/riscv/context.rs
modules/axhal/src/arch/riscv/mod.rs
modules/axhal/src/arch/riscv/signal.S
modules/axhal/src/arch/riscv/trap.rs
modules/axhal/src/arch/x86_64/context.rs
modules/axhal/src/arch/x86_64/mod.rs
modules/axhal/src/arch/x86_64/signal.S
modules/axhal/src/arch/x86_64/syscall.S
modules/axhal/src/arch/x86_64/trap.rs
modules/axhal/src/trap.rs
modules/axmm/src/aspace.rs

This PR adds support for signal handling, which includes:
- Refactoring `UspaceContext` & `TrapFrame` so that more registers (including argx, retval, ra) are exposed
- Reserving a page as signal trampoline during linking
- Adding generic trap handling to handle any trap, allowing us to capture the returning from kernel to uspace
- Fixing `AddrSpace`: data of linear mapping should not be copied in `clone_or_err`
Test results at [starry-next#signal](https://github.com/Mivik/starry-next/tree/signal)
| riscv | x86_64 | loongarch64 |
|-|-|-|
|![image](https://github.com/user-attachments/assets/245728ea-a5de-4f1a-9190-17f4f564fd2b)|![image](https://github.com/user-attachments/assets/beb76f52-18a8-4ec2-a39c-6526f20425af)|![屏幕截图_20250327_100745](https://github.com/user-attachments/assets/6b363369- …

Add support for signal handling

---

Cargo.lock
modules/axsync/Cargo.toml
modules/axsync/src/lib.rs
modules/axsync/src/mutex.rs

This PR adapts axsync::Mutex with [lock_api](https://docs.rs/lock_api).
It adds the `RawMutex` type and allows the use of more complete APIs provided by lock_api, such as `lock_arc`, `map`, etc.
1. Maybe we should also adapt [kspin](https://docs.rs/kspin/latest/kspin/) to lock_api.
2. Perhaps we can further implement more traits in lock_api later, such as `RawMutexTimed` or `RawRwLock`.
3. [spin](https://docs.rs/spin) is compatible with lock_api.

feat: lock_api

---

modules/axhal/src/arch/aarch64/context.rs
modules/axhal/src/arch/aarch64/trap.S
modules/axhal/src/arch/aarch64/trap.rs
modules/axhal/src/arch/loongarch64/context.rs
modules/axhal/src/arch/loongarch64/trap.rs
modules/axhal/src/arch/riscv/context.rs
modules/axhal/src/arch/riscv/trap.rs
modules/axhal/src/arch/x86_64/context.rs
modules/axhal/src/arch/x86_64/mod.rs
modules/axhal/src/arch/x86_64/syscall.S
modules/axhal/src/arch/x86_64/syscall.rs
modules/axhal/src/arch/x86_64/tls.rs
modules/axhal/src/arch/x86_64/trap.S
modules/axhal/src/arch/x86_64/trap.rs
modules/axhal/src/trap.rs
modules/axtask/src/task.rs

This PR fixes two issues in axhal:
1. The instruction pointer should be bumped before calling `handle_syscall` on riscv64 and loongarch64.
2. Isolation between user-level TLS and kernel-level TLS is not considered on aarch64 and x86_64.
Also note that as a result, the `arch_prctl` implementation should write to `TrapFrame` so it's necessary to change `handle_syscall` to accept a `&mut TrapFrame`.
The benefits of this PR:
- The instruction pointer in the `TrapFrame` we get in syscall handlers is unified on all four platforms, that is, it points to the next instruction of the syscall. This again has two benefits:
- We no longer need to manually bump it when cloning a task (see https://github.com/oscomp/starry-next/blob/0c84473be8a7e3876c62d69f63c2853f404df3a9/api/src/imp/task/clone.rs#L113-L …

Fix ip bump and tls isolation for hal

---

modules/axtask/src/wait_queue.rs

Due to a typo current `WaitQueue::requeue` returns incorrect value if `count` is greater than queue size. Also this PR prevented locking again if `tasks.is_empty()`.

Fix: `WaitQueue::requeue` wrong implementation

---

modules/axhal/src/arch/loongarch64/context.rs
modules/axhal/src/arch/loongarch64/macros.rs

Implement floating point support for loongarch
https://github.com/oscomp/arceos/issues/26
Save and restore fp registers on context switch.
use starry-next to test
```c
// libc/c/float
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>   // 用于 uintptr_t
#include <math.h>     // 用于 fabs
#include <unistd.h>   // 对于 fork, _exit, usleep/sched_yield
#include <sys/wait.h> // 对于 waitpid
#define NUM_FP_REGS 32
#define FP_VAL_EQUAL_THRESHOLD 1e-12
#define NUM_CHILD_PROCESSES 2 // 创建多少个子进程进行测试
#define YIELD_ITERATIONS 5    // 每个子进程尝试让出CPU的次数
// 为每个子进程准备的不同的初始浮点值
double child_initial_values[NUM_CHILD_PROCESSES][NUM_FP_REGS];
// 每个子进程从浮点寄存器恢复后读回的值 (在子进程的栈上分配)
// 初始化所有子进程的测试数据
void initialize_fp_values_for_children()
{
for (int child_idx = 0; child_idx < NUM_CHILD_PROCESSES; …
```

feat[axhal]: implement floating point support for loongarch64

---

modules/axhal/src/arch/aarch64/trap.rs
modules/axhal/src/arch/loongarch64/trap.rs
modules/axhal/src/arch/riscv/trap.rs
modules/axhal/src/arch/x86_64/syscall.rs
modules/axhal/src/arch/x86_64/trap.rs

The interrupt is turned off after `exception_handler` ends before `trap_handler` ends
https://github.com/oscomp/arceos/pull/42#issuecomment-2883966765
Add the `mask_interrupts_after_exception` function
* Complements `unmask_interrupts_for_exception` and improves readability
> Tips: Please provide the **test results** of running testcases for [starry-next](https://github.com/oscomp/starry-next) on the commit corresponding to your PR. You can paste it here in the form of a screenshot, or provide a CI link to **a branch or fork of starry-next** for us to review.
Before `trap_handler` ends, add `asser!(!super::irqs_enabled())`, again before `syscall_handler` ends in x86_64.

fix: Disable interrupts before switching contexts

---

modules/axmm/src/aspace.rs

`handle_cow_fault` in `populate_area` uses pte flags, which has removed the write flag.
Should use the `area.flags()`.

fix: Incorrect flags for `handle_cow_fault` in `populate_area`
